[package]
authors = ["Jack Grigg <str4d@i2pmail.org>", "Jeff Burdges <burdges@gnunet.org>"]
description = "Aggregate BLS-like signatures"
documentation = "https://docs.rs/bls-like"
homepage = "https://github.com/w3f/bls"
license = "MIT/Apache-2.0"
name = "bls-like"
repository = "https://github.com/w3f/bls"
version = "0.1.0"

[dependencies]
arrayref = "0.3"
rand = "0.7"
rand_core = "0.5"
rand_chacha = "0.2"
ff = { version = "0.4", features = ["derive"] }
sha3 = "0.8"
#zexe dependencies
algebra-core = { git = "https://github.com/scipr-lab/zexe" }
algebra = { git = "https://github.com/scipr-lab/zexe", features = ["bls12_381"] }

# [dependencies.merlin] 
# version = "1.1.0"
## features = ["debug-transcript"]

#[dependencies]


# [dependencies.pairing]
# git = "https://github.com/burdges/pairing"
# branch = "master-hashing-derives_borrows_etc0"
## historical:
## branch = "derives_borrows_etc0"
## git = "https://github.com/mmaker/pairing"
## branch = "master"

[dependencies.serde]
version = "^1.0"
default-features = false
optional = true

[dependencies.thiserror]
version = "1.0.10"
