[package]
authors = ["Jack Grigg <str4d@i2pmail.org>", "Jeff Burdges <burdges@gnunet.org>"]
description = "Aggregate BLS-like signatures"
documentation = "https://docs.rs/bls-like"
homepage = "https://github.com/w3f/bls"
license = "MIT/Apache-2.0"
name = "bls-like"
repository = "https://github.com/w3f/bls"
version = "0.1.0"
edition = "2018"

[dependencies]
arrayref = "0.3"
rand = "0.4"
ff = { version = "0.8", features = ["derive"] }
sha3 = "0.8"
digest = "0.9.0"

# [dependencies.merlin] 
# version = "1.1.0"
## features = ["debug-transcript"]

#[dependencies.paired]
#version = "0.20"
# git = "https://github.com/filecoin-project/pairing"
[dependencies.pairing]
version = "0.18"

# [dependencies.pairing]
# git = "https://github.com/burdges/pairing"
# branch = "master-hashing-derives_borrows_etc0"
## historical:
## branch = "derives_borrows_etc0"
## git = "https://github.com/mmaker/pairing"
## branch = "master"
[dependencies.zeroize]
version = "1.0.0"
default-features = false
features = ["zeroize_derive"]


[dependencies.serde]
version = "^1.0"
default-features = false
optional = true

[dev-dependencies]
rand= "0.7.3"
